### ISSUE TITLE
Ubuntu and win running pipline

### ISSUE THREAD

**Issue by tutu96177** [ming71/rotate-yolov3#1]
Hi Ming71,
This projects is a Creative idea, can you put this project in Ubuntu and Win running pipline, thank you very much. Looking forward to your reply.

**Comment by ming71** [comment]
:smile: Thanks. You can refer to [this repo](https://github.com/ultralytics/yolov3) for a quick start, nothing different but installation for CUDA RNMS, it's not a problem.
As for windows, sorry  I've not tried it.

**Comment by tutu96177** [comment]
> 😄 Thanks. You can refer to [this repo](https://github.com/ultralytics/yolov3) for a quick start, nothing different but installation for CUDA RNMS, it's not a problem.
> As for windows, sorry I've not tried it.

Thanks, can you put your trained model on Baidudisk or Googledisk , I want to run inference on DOTA datasets .  If you don't mind, you can add my QQ, I want to cooperate with you, thank you.(961771865)

**Comment by ming71** [comment]
> > 😄 Thanks. You can refer to [this repo](https://github.com/ultralytics/yolov3) for a quick start, nothing different but installation for CUDA RNMS, it's not a problem.
> > As for windows, sorry I've not tried it.
> 
> Thanks, can you put your trained model on Baidudisk or Googledisk , I want to run inference on DOTA datasets . If you don't mind, you can add my QQ, I want to cooperate with you, thank you.(961771865)

Sorry, I don't have model on hand, it was left in laboratory and I cannot return back there due to COVID-19  you know.

**Comment by tutu96177** [comment]
> > > 😄 Thanks. You can refer to [this repo](https://github.com/ultralytics/yolov3) for a quick start, nothing different but installation for CUDA RNMS, it's not a problem.
> > > As for windows, sorry I've not tried it.
> > 
> > 
> > Thanks, can you put your trained model on Baidudisk or Googledisk , I want to run inference on DOTA datasets . If you don't mind, you can add my QQ, I want to cooperate with you, thank you.(961771865)
> 
> Sorry, I don't have model on hand, it was left in laboratory and I cannot return back there due to COVID-19 you know.



> > > 😄 Thanks. You can refer to [this repo](https://github.com/ultralytics/yolov3) for a quick start, nothing different but installation for CUDA RNMS, it's not a problem.
> > > As for windows, sorry I've not tried it.
> > 
> > 
> > Thanks, can you put your trained model on Baidudisk or Googledisk , I want to run inference on DOTA datasets . If you don't mind, you can add my QQ, I want to cooperate with you, thank you.(961771865)
> 
> Sorry, I don't have model on hand, it was left in laboratory and I cannot return back there due to COVID-19 you know.
Thank you for your reply. Can you provide a pipeline for the model of the revised code training DOTA dataset
?

**Comment by tutu96177** [comment]
> > > > 😄 Thanks. You can refer to [this repo](https://github.com/ultralytics/yolov3) for a quick start, nothing different but installation for CUDA RNMS, it's not a problem.
> > > > As for windows, sorry I've not tried it.
> > > 
> > > 
> > > Thanks, can you put your trained model on Baidudisk or Googledisk , I want to run inference on DOTA datasets . If you don't mind, you can add my QQ, I want to cooperate with you, thank you.(961771865)
> > 
> > 
> > Sorry, I don't have model on hand, it was left in laboratory and I cannot return back there due to COVID-19 you know.
> 
> > > > 😄 Thanks. You can refer to [this repo](https://github.com/ultralytics/yolov3) for a quick start, nothing different but installation for CUDA RNMS, it's not a problem.
> > > > As for windows, sorry I've not tried it.
> > > 
> > > 
> > > Thanks, can you put your trained model on Baidudisk or Googledisk , I want to run inference on DOTA datasets . If you don't mind, you can add my QQ, I want to cooperate with you, thank you.(961771865)
> > 
> > 
> > Sorry, I don't have model on hand, it was left in laboratory and I cannot return back there due to COVID-19 you know.
> > Thank you for your reply. Can you provide a pipeline for the model of the revised code training DOTA dataset
> > ?

Thank you for your reply. Can you provide a pipeline for the model of the revised code training DOTA dataset？

**Comment by ming71** [comment]
I don't try to train on DOTA dataset in this repo, only HRSC2016 and ICDAR15 supported.If you want, you can write yourself refer to [DOTA_devkit](https://github.com/CAPTAIN-WHU/DOTA_devkit).

And I'll release a stronger codebase with more accurate results later in my github, it will support DOTA, HRSC2016, ICDAR2015 and UCAS-AOD datasets.

**Comment by tutu96177** [comment]
> I don't try to train on DOTA dataset in this repo, only HRSC2016 and ICDAR15 supported.If you want, you can write yourself refer to [DOTA_devkit](https://github.com/CAPTAIN-WHU/DOTA_devkit).
> 
> And I'll release a stronger codebase with more accurate results later in my github, it will support DOTA, HRSC2016, ICDAR2015 and UCAS-AOD datasets.

Thank you very much for your Suggestions and look forward to your sharing. May I ask when the new version of the code will be available?

**Comment by ming71** [comment]
> > I don't try to train on DOTA dataset in this repo, only HRSC2016 and ICDAR15 supported.If you want, you can write yourself refer to [DOTA_devkit](https://github.com/CAPTAIN-WHU/DOTA_devkit).
> > And I'll release a stronger codebase with more accurate results later in my github, it will support DOTA, HRSC2016, ICDAR2015 and UCAS-AOD datasets.
> 
> Thank you very much for your Suggestions and look forward to your sharing. May I ask when the new version of the code will be available?

Maybe a month or so.
