### ISSUE TITLE
还有个问题，对于HRSC2016这样的数据集，如果不使用dcn的话效果会差很多么？

### ISSUE THREAD

**Issue by clw5180** [ming71/rotate-yolov3#10]
RT

**Comment by ming71** [comment]
个人使用情况来看，DCN会使得收稍微慢一点，需要一定次数的迭代让卷积核对齐目标，但是性能来说比较稳定，会有一定的提升。不加效果也不至于太差，在HRSC2016的level任务上mAP能达到85。
