### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by get36** [ming71/rotate-yolov3#15]
大佬你好，我在运行过程中遇到报错：
from utils.nms.r_nms import r_nms
ModuleNotFoundError: No module named 'utils.nms.r_nms
没有这个r_nms，请问是没上传这个文件吗？

**Comment by WJ1214** [comment]
> 大佬你好，我在运行过程中遇到报错：
> from utils.nms.r_nms import r_nms
> ModuleNotFoundError: No module named 'utils.nms.r_nms
> 没有这个r_nms，请问是没上传这个文件吗？

这个是个torch extension的模块，需要你编译一下

**Comment by get36** [comment]
谢谢大佬，这个问题解决了。
请问icdar_608_care.txt这个文件具体是什么格式阿？我用作者给的kmeans.py运行出了结果，然是代码并没有写那个txt文件，可以发个格式给我参考下吗？

**Comment by WJ1214** [comment]
> 谢谢大佬，这个问题解决了。
> 请问icdar_608_care.txt这个文件具体是什么格式阿？我用作者给的kmeans.py运行出了结果，然是代码并没有写那个txt文件，可以发个格式给我参考下吗？

我的anchor在另一个数据集上聚类来的，就只有anchor的宽高设置，大概是这样
![image](https://user-images.githubusercontent.com/51085092/90603985-ba49e780-e22e-11ea-80d2-91e7f3c40bc9.png)
具体anchor程序怎么解析的你可以看utils/parse_config.py这个文件里面的cfg2anchors程序

**Comment by get36** [comment]
恩恩，明白了，谢谢！ @WJ1214

**Comment by get36** [comment]
大佬你好，请问你有遇到过这个问题吗？
name 'ORConv2d' is not defined

**Comment by WJ1214** [comment]
这个项目里面的ORN模块他没实现，你换个其他不包含这个ORN模块的配置文件就正常了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "get36"<notifications@github.com&gt;; 
发送时间: 2020年8月19日(星期三) 下午3:34
收件人: "ming71/rotate-yolov3"<rotate-yolov3@noreply.github.com&gt;; 
抄送: "null"<1115794188@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ming71/rotate-yolov3] 代码运行问题 (#15)





 
大佬你好，请问你有遇到过这个问题吗？
 name 'ORConv2d' is not defined

**Comment by get36** [comment]
谢谢！还有一个问题，我想换成我的数据集，作者还给了一个项目作参考，我去看了下，那个项目里只说了训练和测试的图片，并不知道他的标签文件是什么格式，大佬有做好的标签文件看下吗？

**Comment by WJ1214** [comment]
> 谢谢！还有一个问题，我想换成我的数据集，作者还给了一个项目作参考，我去看了下，那个项目里只说了训练和测试的图片，并不知道他的标签文件是什么格式，大佬有做好的标签文件看下吗？

你按照yolov3数据集的格式处理你的数据集就行[yolov3](https://github.com/ultralytics/yolov3l)，具体方式在这[train custom dataset](https://github.com/ultralytics/yolov3/wiki/Train-Custom-Data)

**Comment by WJ1214** [comment]
> 谢谢！还有一个问题，我想换成我的数据集，作者还给了一个项目作参考，我去看了下，那个项目里只说了训练和测试的图片，并不知道他的标签文件是什么格式，大佬有做好的标签文件看下吗？
![image](https://user-images.githubusercontent.com/51085092/90611445-524cce80-e239-11ea-9372-476a4598a3be.png)
这是我的label格式，第一个是目标种类，最后一个是角度，中间分别是xywh

**Comment by get36** [comment]
太感谢了！@WJ1214

**Comment by get36** [comment]
你好，请问你在跑程序过程中是否出现了这个问题：
Expected Ptr<cv::UMat> for argument 'img'
在utils.py 534行，貌似是在图像中画框的过程

**Comment by WJ1214** [comment]
好像出现过，不记得了，我后面应该是把可视化的一些代码注释掉了





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "get36"<notifications@github.com&gt;; 
发送时间: 2020年8月19日(星期三) 下午5:18
收件人: "ming71/rotate-yolov3"<rotate-yolov3@noreply.github.com&gt;; 
抄送: "null"<1115794188@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ming71/rotate-yolov3] 代码运行问题 (#15)





 
你好，请问你在跑程序过程中是否出现了这个问题：
 Expected Ptrcv::UMat for argument 'img'
 在utils.py 534行，貌似是在图像中画框的过程

**Comment by get36** [comment]
恩恩，还有一个loss.py中的torch.where的问题，缺少两个参数，请问这怎么弄得呢？

**Comment by WJ1214** [comment]
报错是什么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "get36"<notifications@github.com&gt;; 
发送时间: 2020年8月19日(星期三) 下午5:26
收件人: "ming71/rotate-yolov3"<rotate-yolov3@noreply.github.com&gt;; 
抄送: "null"<1115794188@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ming71/rotate-yolov3] 代码运行问题 (#15)





 
恩恩，还有一个loss.py中的torch.where的问题，缺少两个参数，请问这怎么弄得呢？

**Comment by get36** [comment]
where() missing 2 required positional argument: "input", "other"
loss.py 384行

**Comment by WJ1214** [comment]
我没遇到过这个报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "get36"<notifications@github.com&gt;; 
发送时间: 2020年8月19日(星期三) 下午5:28
收件人: "ming71/rotate-yolov3"<rotate-yolov3@noreply.github.com&gt;; 
抄送: "null"<1115794188@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ming71/rotate-yolov3] 代码运行问题 (#15)





 
where() missing 2 required positional argument: "input", "other"
 loss.py 384行

**Comment by get36** [comment]
恩......我搜了下 torch.where确实要三个参数啊...代码中只给了一个

**Comment by WJ1214** [comment]
不清楚。。。我这行代码和他是一样的，可能后面作者添加了什么，你调试一下吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "get36"<notifications@github.com&gt;; 
发送时间: 2020年8月19日(星期三) 下午5:33
收件人: "ming71/rotate-yolov3"<rotate-yolov3@noreply.github.com&gt;; 
抄送: "null"<1115794188@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ming71/rotate-yolov3] 代码运行问题 (#15)





 
恩......我搜了下 torch.where确实要三个参数啊...代码中只给了一个

**Comment by get36** [comment]
大佬，请问loss.py 376你有报错吗？
 assert c.max() <= model.nc, 'Target classes exceed model classes'
Target classes exceed model classes
似乎是在读取label的时候读到了其他的数，我的nc=1，label也都是0

**Comment by WJ1214** [comment]
你检查一下是不是数据集标注有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "get36"<notifications@github.com&gt;; 
发送时间: 2020年8月19日(星期三) 晚上6:16
收件人: "ming71/rotate-yolov3"<rotate-yolov3@noreply.github.com&gt;; 
抄送: "null"<1115794188@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ming71/rotate-yolov3] 代码运行问题 (#15)





 
大佬，请问loss.py 376你有报错吗？
 assert c.max() <= model.nc, 'Target classes exceed model classes'
 Target classes exceed model classes
 似乎是在读取label的时候读到了其他的数，我的nc=1，label也都是0

**Comment by get36** [comment]
我debug了一下，不知道为什么，我的targets在一个7位数，这对吗？

**Comment by WJ1214** [comment]
。。。。你这应该是标注出问题了吧？你看看你把原本的数据集转换成yolo类型之后有没有转换错误的地方




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "get36"<notifications@github.com&gt;; 
发送时间: 2020年8月19日(星期三) 晚上6:28
收件人: "ming71/rotate-yolov3"<rotate-yolov3@noreply.github.com&gt;; 
抄送: "null"<1115794188@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ming71/rotate-yolov3] 代码运行问题 (#15)





 
我debug了一下，不知道为什么，我的targets在一个7位数，这对吗？

**Comment by get36** [comment]
我看了下targets确实应该是7位数，在datasets.py的494行，这就不懂了，为什么有7位数，多出来的一位来干嘛？
还有一个问题，我的anchor必须聚16个才行，不然也会报错......

**Comment by WJ1214** [comment]
> 我看了下targets确实应该是7位数，在datasets.py的494行，这就不懂了，为什么有7位数，多出来的一位来干嘛？
> 还有一个问题，我的anchor必须聚16个才行，不然也会报错......

![image](https://user-images.githubusercontent.com/51085092/90625256-ddcf5b00-e24b-11ea-829c-cfe410f4c4d7.png)
7位是因为有一个置信度分数，anchor你看模型怎么解析的吧，我这里是可以用的

**Comment by get36** [comment]
File "/home/ubuntu/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/warmup_scheduler/scheduler.py", line 31, in get_lr
    return self.after_scheduler.get_last_lr()
AttributeError: 'MultiStepLR' object has no attribute 'get_last_lr'
大佬请问你遇到这个错误了吗？

**Comment by WJ1214** [comment]
没有，作者写的scheduler好像有多余的部分，我好像注释了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "get36"<notifications@github.com&gt;; 
发送时间: 2020年8月19日(星期三) 晚上7:26
收件人: "ming71/rotate-yolov3"<rotate-yolov3@noreply.github.com&gt;; 
抄送: "null"<1115794188@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ming71/rotate-yolov3] 代码运行问题 (#15)





 
File "/home/ubuntu/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/warmup_scheduler/scheduler.py", line 31, in get_lr
 return self.after_scheduler.get_last_lr()
 AttributeError: 'MultiStepLR' object has no attribute 'get_last_lr'
 大佬请问你遇到这个错误了吗？

**Comment by xyl-507** [comment]
> 谢谢大佬，这个问题解决了。
> 请问icdar_608_care.txt这个文件具体是什么格式阿？我用作者给的kmeans.py运行出了结果，然是代码并没有写那个txt文件，可以发个格式给我参考下吗？

大佬，我在/utils/nms里面运行`python setup.py clean && python setup.py develop`
出现问题如下
`running clean
removing 'build\temp.win-amd64-3.7' (and everything under it)
removing 'build'
running develop
running egg_info
writing r_nms.egg-info\PKG-INFO
writing dependency_links to r_nms.egg-info\dependency_links.txt
writing top-level names to r_nms.egg-info\top_level.txt
reading manifest file 'r_nms.egg-info\SOURCES.txt'
writing manifest file 'r_nms.egg-info\SOURCES.txt'
running build_ext
E:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py:238: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'r_nms' extension
creating D:\code\rotate-yolov3-master\utils\nms\build
creating D:\code\rotate-yolov3-master\utils\nms\build\temp.win-amd64-3.7
creating D:\code\rotate-yolov3-master\utils\nms\build\temp.win-amd64-3.7\Release
creating D:\code\rotate-yolov3-master\utils\nms\build\temp.win-amd64-3.7\Release\src
Emitting ninja build file D:\code\rotate-yolov3-master\utils\nms\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IE:\Anaconda3\envs\pytorch\lib\site-packages\torch\include -IE:\Anaconda3\envs\pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IE:\Anaconda3\envs\pytorch\lib\site-packages\to
rch\include\TH -IE:\Anaconda3\envs\pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IE:\Anaconda3\envs\pytorch\include -IE:\Anaconda3\envs\pytorch\include "-IC:\Program Files (x86)\Microsoft Visual St
udio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" -c
 D:\code\rotate-yolov3-master\utils\nms\src\rotate_polygon_nms.cpp /FoD:\code\rotate-yolov3-master\utils\nms\build\temp.win-amd64-3.7\Release\src/rotate_polygon_nms.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=r_nms -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++
14
**FAILED: D:/code/rotate-yolov3-master/utils/nms/build/temp.win-amd64-3.7/Release/src/rotate_polygon_nms.obj**
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IE:\Anaconda3\envs\pytorch\lib\site-packages\torch\include -IE:\Anaconda3\envs\pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IE:\Anaconda3\envs\pytorch\lib\site-packages\torch\in
clude\TH -IE:\Anaconda3\envs\pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IE:\Anaconda3\envs\pytorch\include -IE:\Anaconda3\envs\pytorch\include "-IC:\Program Files (x86)\Microsoft Visual Studio 1
4.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" -c D:\co
de\rotate-yolov3-master\utils\nms\src\rotate_polygon_nms.cpp /FoD:\code\rotate-yolov3-master\utils\nms\build\temp.win-amd64-3.7\Release\src/rotate_polygon_nms.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=r_nms -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
**ninja: fatal: ReadFile: 句柄无效。**

Traceback (most recent call last):
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1423, in _run_ninja_build
    check=True)
  File "E:\Anaconda3\envs\pytorch\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "E:\Anaconda3\envs\pytorch\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "E:\Anaconda3\envs\pytorch\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "E:\Anaconda3\envs\pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\command\develop.py", line 38, in run
    self.install_for_development()
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\command\develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "E:\Anaconda3\envs\pytorch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "E:\Anaconda3\envs\pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "E:\Anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "E:\Anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "E:\Anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "E:\Anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 585, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
**RuntimeError: Error compiling objects for extension**
`
能不能请教一下您，怎么解决的？ @get36

**Comment by ming71** [comment]
> 这个项目里面的ORN模块他没实现，你换个其他不包含这个ORN模块的配置文件就正常了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "get36"<notifications@github.com&gt;; 发送时间: 2020年8月19日(星期三) 下午3:34 收件人: "ming71/rotate-yolov3"<rotate-yolov3@noreply.github.com&gt;; 抄送: "null"<1115794188@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [ming71/rotate-yolov3] 代码运行问题 (#15) 大佬你好，请问你有遇到过这个问题吗？ name 'ORConv2d' is not defined — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

之前的代码不完善，已重新上传更新ORN修复了很多bug，跑通没问题。但是loss计算和target_build部分有点小问题导致precision上不去，mAP比较低，暂时不维护了，有问题可以我尽量能解答及时回答。

**Comment by SonwYang** [comment]
请问下模型的配置文件是不是没有上传，我没找到。。。。。

**Comment by ming71** [comment]
> 请问下模型的配置文件是不是没有上传，我没找到。。。。。

已上传

**Comment by SonwYang** [comment]
好的，谢谢

**Comment by stevenXS** [comment]
@WJ1214  你好，请问你在哪个环境下运行的setup.py

**Comment by WJ1214** [comment]
> @WJ1214 你好，请问你在哪个环境下运行的setup.py

python3.7 pytorch1.4 cuda10.2

**Comment by stevenXS** [comment]
请问大佬 遇到过这个问题么，我们用的（torch1.6 python3.6 cuda11.0）----AT_CHECK未定义









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WJ1214"<notifications@github.com&gt;; 
发送时间: 2020年10月12日(星期一) 下午2:35
收件人: "ming71/rotate-yolov3"<rotate-yolov3@noreply.github.com&gt;; 
抄送: ".Joshua"<1165160978@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ming71/rotate-yolov3] 代码运行问题 (#15)





  
@WJ1214 你好，请问你在哪个环境下运行的setup.py
  
python3.7 pytorch1.4 cuda10.2

**Comment by WJ1214** [comment]
> 请问大佬 遇到过这个问题么，我们用的（torch1.6 python3.6 cuda11.0）----AT_CHECK未定义
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WJ1214"<notifications@github.com&gt;; 发送时间: 2020年10月12日(星期一) 下午2:35 收件人: "ming71/rotate-yolov3"<rotate-yolov3@noreply.github.com&gt;; 抄送: ".Joshua"<1165160978@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [ming71/rotate-yolov3] 代码运行问题 (#15) @WJ1214 你好，请问你在哪个环境下运行的setup.py python3.7 pytorch1.4 cuda10.2 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

没有碰到过，另外不太建议用这个项目作为改进基础，因为作者代码因为缺失有一些问题，而且我在自己任务的数据集上训练的结果不太好，可能是yolo不太适合旋转目标检测的任务（更大可能是我有某些重大bug没改过来。。。），如果不追求很高的速度，可以看看遥感检测领域相关的代码，或者看看检测旋转目标的CenterNet

**Comment by stevenXS** [comment]
非常感谢你的建议~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WJ1214"<notifications@github.com&gt;; 
发送时间: 2020年10月12日(星期一) 下午2:45
收件人: "ming71/rotate-yolov3"<rotate-yolov3@noreply.github.com&gt;; 
抄送: ".Joshua"<1165160978@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ming71/rotate-yolov3] 代码运行问题 (#15)





  
请问大佬 遇到过这个问题么，我们用的（torch1.6 python3.6 cuda11.0）----AT_CHECK未定义
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WJ1214"<notifications@github.com&gt;; 发送时间: 2020年10月12日(星期一) 下午2:35 收件人: "ming71/rotate-yolov3"<rotate-yolov3@noreply.github.com&gt;; 抄送: ".Joshua"<1165160978@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [ming71/rotate-yolov3] 代码运行问题 (#15) @WJ1214 你好，请问你在哪个环境下运行的setup.py python3.7 pytorch1.4 cuda10.2 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
没有碰到过，另外不太建议用这个项目作为改进基础，因为作者代码因为缺失有一些问题，而且我在自己任务的数据集上训练的结果不太好，可能是yolo不太适合旋转目标检测的任务（更大可能是我有某些重大bug没改过来。。。），如果不追求很高的速度，可以看看遥感检测领域相关的代码，或者看看检测旋转目标的CenterNet

**Comment by jumoran** [comment]
> > 大佬你好，我在运行过程中遇到报错：
> > from utils.nms.r_nms import r_nms
> > ModuleNotFoundError: No module named 'utils.nms.r_nms
> > 没有这个r_nms，请问是没上传这个文件吗？
> 
> 这个是个torch extension的模块，需要你编译一下

老师您好，我这个编译的时候出错，麻烦您帮我看看是什么原因？
![image](https://user-images.githubusercontent.com/50037652/116370387-eea18900-a83c-11eb-8e18-072b71a1315c.png)

**Comment by ming71** [comment]
> 译的时候出错，

一般是torch cuda的版本问题

**Comment by ming71** [comment]
> AT_CHECK

这个orn编译只适用于cuda.9x和10.x. `AT_CHECK`报错是11.x的问题,如果硬要用,可以将其改为`TORCH_CHECK`再编译试试.
