### ISSUE TITLE
数据标注格式

### ISSUE THREAD

**Issue by Lmoer** [ming71/rotate-yolov3#16]
请问一下LZ，旋转框的数据标注格式是怎么样的，如果可以，对于完整的pipline，可否写一个类似于https://github.com/ultralytics/yolov3的pipline readme

**Comment by ming71** [comment]
这里的hrsc数据集用的官方标注的五参数表示。但是实际训练前转为txt文件，可以参考我这个repo的实现：[converter](https://github.com/ming71/toolbox/blob/master/converter/xml2yolo.py)

**Comment by Lmoer** [comment]
LZ如果可以，对于完整的pipline，可否写一个类似于https://github.com/ultralytics/yolov3 的 pipline readme,代码看得我一头雾水

**Comment by edwardnguyen1705** [comment]
Dear @ming71 ,
Thank you for sharing your work.
I am not clear about the `rbbox` annotation of the [HRSC](https://sites.google.com/site/hrsc2016/annotations) dataset. I guess it is in `[xc, yc, w, h, ang]`, but I do not know how w, h are measured, parallel to the image coordinates or from the cv2.minAreaRect, as well as the `ang`? Here is my dataset label format `rbbox = [xc, yc, w, h, ang]:` 
```
rect = cv2.minAreaRect(hull)
xc, yc = rect[0][0], rect[0][1]
w, h = rect[1][0], rect[1][1]
ang = rect[2]
rbbox = [xc, yc, w, h, ang]
```

However, according to this [source](https://namkeenman.wordpress.com/2015/12/18/open-cv-determine-angle-of-rotatedrect-minarearect/), the `ang` varies between -0 to -90 and the vertex arrangement is quite specific.

When you train the HRSC dataset:

- `w` is always larger than `h`?

- Where is the origin to measure the `ang` (`-pi/2, pi/2`)? 

Thank you for your time.

**Comment by ming71** [comment]
> e is my

hello, u r right, the implementation here does not consider the periodicity of the angle and strictly defination the width and height, which may lead to ambiguity in the prediction results.I have not been able to optimize before.
As for the annotation format, I use the same format as yolov3, and the additional angle variable is introduced, specifically, (cx, cy, w, h, a), in which cx, cy, w, h are normalized to (0,1). More details can be found [here](https://github.com/ming71/toolbox/blob/b06cdfc188fd8b68f58eebf633f6556e240c579a/converter/xml2yolo.py#L76).

**Comment by Jihnjockey** [comment]
> > e is my
> 
> hello, u r right, the implementation here does not consider the periodicity of the angle and strictly defination the width and height, which may lead to ambiguity in the prediction results.I have not been able to optimize before.
> As for the annotation format, I use the same format as yolov3, and the additional angle variable is introduced, specifically, (cx, cy, w, h, a), in which cx, cy, w, h are normalized to (0,1). More details can be found [here](https://github.com/ming71/toolbox/blob/b06cdfc188fd8b68f58eebf633f6556e240c579a/converter/xml2yolo.py#L76).

cx cy我知道，cx/1920 ，cy/1080，但是w和h怎么归一化呢，anchor是有角度的，总不能w/1920，h/1080吧

**Comment by ming71** [comment]
w和h也用图像尺度归一化,角度不用处理.
