### ISSUE TITLE
Training on custom dataset Error

### ISSUE THREAD

**Issue by ghost** [ming71/rotate-yolov3#18]
Hi, ming71, Thanks for your repo, it is very wonderful.
when I training on custom dataset there is a problem, file train.py import test.py. and it import r_nms   from utils.nms.r_nms. But No module named 'utils.nms.r_nms. 
How can I get this file ? Thanks.

**Comment by ming71** [comment]
You need to compile related files first. Run `sh make.sh` and it will work.
