### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ZeKunZhang1998** [ming71/rotate-yolov3#19]
Hello，what is the format of the dataset？

**Comment by ming71** [comment]
training sample is available now, check it [here](https://github.com/ming71/rotate-yolov3/tree/master/HRSC2016/train).

**Comment by SonwYang** [comment]
Can you provide the dataset of ship?

**Comment by ZeKunZhang1998** [comment]
> training sample is available now, check it [here](https://github.com/ming71/rotate-yolov3/tree/master/HRSC2016/train).

Thanks，is the same with yolo [x,y,w,h,theta]

**Comment by ZeKunZhang1998** [comment]
> Can you provide the dataset of ship?

Sorry,It is a private dataset.

**Comment by ming71** [comment]
> Can you provide the dataset of ship?

The dataset used for ship detection here is HRSC2016, you can download yourself.

**Comment by ZeKunZhang1998** [comment]
> training sample is available now, check it here.

Hi，how to modify the cfg when i train on my dataset?

**Comment by ming71** [comment]
class names, num classes, and the channel of the output layer.
