### ISSUE TITLE
Running Code

### ISSUE THREAD

**Issue by jivkovic** [ming71/rotate-yolov3#2]
Hi, thanks for the effort.

Could you update readme with some basic steps how to use the scripts?
I'm getting "OSError: utils/kmeans/icdar_608_care.txt not found." error when running test.py, train.py and detect.py.

I am going through code, but some basic info would be very helpful.

Thanks

**Comment by ming71** [comment]
`icdar_608_care.txt` sets the initial anchors generated via kmeans, you need to run `kmeans.py`  refer to my  implement [here](https://github.com/ming71/toolbox/blob/master/kmeans.py).
I'll update training pipeline and latest codes after return school.(maybe in Sep.)
