### ISSUE TITLE
what is your version?

### ISSUE THREAD

**Issue by ZeKunZhang1998** [ming71/rotate-yolov3#21]
/content/drive/My Drive/rotate-yolov3/utils/nms
running install
running bdist_egg
running egg_info
writing r_nms.egg-info/PKG-INFO
writing dependency_links to r_nms.egg-info/dependency_links.txt
writing top-level names to r_nms.egg-info/top_level.txt
/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py:335: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
writing manifest file 'r_nms.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'r_nms' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c src/rotate_polygon_nms.cpp -o build/temp.linux-x86_64-3.6/src/rotate_polygon_nms.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=r_nms -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Parallel.h:149:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                 from src/rotate_polygon_nms.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
src/rotate_polygon_nms.cpp: In function ‘at::Tensor r_nms(const at::Tensor&, float)’:
src/rotate_polygon_nms.cpp:3:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                       ^
src/rotate_polygon_nms.cpp:8:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                 from src/rotate_polygon_nms.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
src/rotate_polygon_nms.cpp:3:23: error: ‘AT_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
src/rotate_polygon_nms.cpp:8:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
src/rotate_polygon_nms.cpp:3:23: note: suggested alternative: ‘DCHECK’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
src/rotate_polygon_nms.cpp:8:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

I met this when i compile this program

**Comment by ghost** [comment]
ya, I also had the same problem when i try compile make.sh to get r_nms file :3 
can you share the file publicly, thanks you so much @ming71

**Comment by ming71** [comment]
It may be caused by the mismatched version of cuda and pytorch. I recompiled RNMS and still didn't report any error.
My environment:
* CUDA 10.0
* pytorch 1.2
* Ubuntu 16.04
* gcc 5.4.0

**Comment by ghost** [comment]
I try in my server, colab and they both get errors,
Could you update RNMS to this repo ? thanks

**Comment by ming71** [comment]
> I try in my server, colab and they both get errors,
> Could you update RNMS to this repo ? thanks

Hi, the current version of RNMS is already the latest, you should find other reasons that cause compilation failure.

**Comment by ZeKunZhang1998** [comment]
hello，how to modefy the parameters when i train my dataset？



---Original---

**Comment by ming71** [comment]
class names, num classes, the channel of the output layers, and k-means.

**Comment by ming71** [comment]
> /content/drive/My Drive/rotate-yolov3/utils/nms running install running bdist_egg running egg_info writing r_nms.egg-info/PKG-INFO writing dependency_links to r_nms.egg-info/dependency_links.txt writing top-level names to r_nms.egg-info/top_level.txt /usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py:335: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend. warnings.warn(msg.format('we could not find ninja.')) writing manifest file 'r_nms.egg-info/SOURCES.txt' installing library code to build/bdist.linux-x86_64/egg running install_lib running build_ext building 'r_nms' extension x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c src/rotate_polygon_nms.cpp -o build/temp.linux-x86_64-3.6/src/rotate_polygon_nms.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=r_nms -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14 In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Parallel.h:149:0, from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/utils.h:3, from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5, from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/nn.h:3, from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:7, from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4, from src/rotate_polygon_nms.cpp:1: /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas] #pragma omp parallel for if ((end - begin) >= grain_size)
> 
> src/rotate_polygon_nms.cpp: In function ‘at::Tensor r_nms(const at::Tensor&, float)’: src/rotate_polygon_nms.cpp:3:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations] #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ") ^ src/rotate_polygon_nms.cpp:8:3: note: in expansion of macro ‘CHECK_CUDA’ CHECK_CUDA(dets); ^~~~~~~~~~ In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0, from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4, from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5, from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3, from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4, from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3, from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3, from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3, from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3, from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4, from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4, from src/rotate_polygon_nms.cpp:1: /usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here DeprecatedTypeProperties & type() const { ^~~~ src/rotate_polygon_nms.cpp:3:23: error: ‘AT_CHECK’ was not declared in this scope #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ") ^ src/rotate_polygon_nms.cpp:8:3: note: in expansion of macro ‘CHECK_CUDA’ CHECK_CUDA(dets); ^~~~~~~~~~ src/rotate_polygon_nms.cpp:3:23: note: suggested alternative: ‘DCHECK’ #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ") ^ src/rotate_polygon_nms.cpp:8:3: note: in expansion of macro ‘CHECK_CUDA’ CHECK_CUDA(dets); ^~~~~~~~~~ error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> 
> I met this when i compile this program

Refer to my solution [here](https://github.com/ming71/rotate-yolov3/issues/15#issuecomment-1068666141).
