### ISSUE TITLE
running code error

### ISSUE THREAD

**Issue by CVYang** [ming71/rotate-yolov3#30]
i download the .pt model file and run with command "python detect.py --wights weights/without-matrix.pt  --cfg cfg/***.cfg --source 2".. it doesnt work. i dont know which cfg file is correct. Can you show me a correct command with weights file and cfg file?

**Comment by ming71** [comment]
Refer to this [issue](https://github.com/ming71/rotate-yolov3/issues/38#issuecomment-1068670676).
