### ISSUE TITLE
UCAS_AOD数据集可以跑吗

### ISSUE THREAD

**Issue by AI-cv-llg** [ming71/rotate-yolov3#31]
大佬，UCAS_AOD数据集可以跑吗，map效果是多少，可以简单说一下吗，目前来说哪个效果最好可以说一下不

**Comment by ming71** [comment]
yolov3跑ucas-aod推荐用我这个codebase能跑出80+：[yolov3-polygon](https://github.com/ming71/yolov3-polygon)

**Comment by AI-cv-llg** [comment]
> yolov3跑ucas-aod推荐用我这个codebase能跑出80+：[yolov3-polygon](https://github.com/ming71/yolov3-polygon)

感谢大佬，我一会试一下，这个可以测出来map吧
