### ISSUE TITLE
Question about code getting layer_id

### ISSUE THREAD

**Issue by JJangD** [ming71/rotate-yolov3#32]
Thanks for your great work!

I was trying to train with my own dataset and I got below error. 

```
File "A:\Object detection\rotate-yolov3-ming\rotate-yolov3-master\model\loss.py", line 245, in build_targets j[layer_id][(best_iou_indexes % na) * nt + gt_id] = True
TypeError: only integer tensors of a single element can be converted to an index

```
occurs from here: 

https://github.com/ming71/rotate-yolov3/blob/5d5cf3c16243d5d5ae52b8044d1d8ed2057924d5/model/loss.py#L239

I think below line should be changed to

 layer_id = (best_iou_indexes//na)[0]

Is it right?

**Comment by ming71** [comment]
Refer to this [issue](https://github.com/ming71/rotate-yolov3/issues/38#issuecomment-1068670676).
