### ISSUE TITLE
大佬  我按照你的思路改了个yolov4 但一直要过拟合  请问是什么原因

### ISSUE THREAD

**Issue by 603610959** [ming71/rotate-yolov3#33]
大佬  我按照你的思路改了个yolov4 但一直要过拟合  请问是什么原因

**Comment by 603610959** [comment]
请问是设置回归的角度范围是多少  0~180？ 0~90？ -45~45？

**Comment by 603610959** [comment]
pred_boxes[..., 4] = torch.atan(a) + anchor_a  我这样回归角度正确吗

**Comment by XuLiuSwust** [comment]
hi,可以分享一下你转换的yolov4么？邮箱454724394@qq.com,谢谢   @603610959

**Comment by ming71** [comment]
1. 先用单张图片过拟合训练,查看是否能过拟合(千万注意关掉任何增强,否则无效)
2. 如果不过拟合,可能是角度读取,编解码,以及损失计算的问题
3. 如果能过拟合,可能是训练参数的问题,调小学习率等试试
4. 角度表示方法很多,有长边定义法(0-180).或者opencv方法(旧的opencv是-90-0),都可以.
