### ISSUE TITLE
旋转的先验框？

### ISSUE THREAD

**Issue by lihualilee** [ming71/rotate-yolov3#35]
大佬请问你是怎么样对先验框进行旋转处理的,在原始的yolov3中,有三种尺度的特征层进行预测,每一种尺度又对应3种不同大小的先验框,他们的大小比例是1:1,1:2,2:1左右,那么我觉得1:2和2:1应该属于同一种类别的先验框,只是他们的旋转角度不一样

**Comment by ming71** [comment]
旋转角本身也是一种先验信息,和hbb铺设dense anchor是一样的,只不过多了一个角度先验而已.
直接统一铺设,预测和编解码就行.
