### ISSUE TITLE
老师您好，关于编译nms时候出错

### ISSUE THREAD

**Issue by jumoran** [ming71/rotate-yolov3#36]
在编译make.sh时，出现了下面的错误，请您帮我看看，谢谢。
![image](https://user-images.githubusercontent.com/50037652/116370639-2c061680-a83d-11eb-929a-41e8e137f8bf.png)

**Comment by gexianwei1231** [comment]
请问您解决了吗？

**Comment by ming71** [comment]
参考我[这里](https://github.com/ming71/rotate-yolov3/issues/15#issuecomment-1068666141)的回答.
