### ISSUE TITLE
Could you provide the weight model on HRSC2016 dataset?

### ISSUE THREAD

**Issue by gaowutong** [ming71/rotate-yolov3#38]
Excellent job!
I was trying to train the rotate-yolov3 model with HRSC2016 but the model seems to require a lower version of cuda. However I only have 3090 GPU which only support cuda 10+. I think you have trained it because of what you show in the `Detection Results`. So could you please provide the trained weight model on HRSC2016 dataset?

**Comment by ming71** [comment]
Hello, thanks for your attention. This repository is too old, it is recommended to turn to some recent work on oriented object detection, such as [S2ANet](https://github.com/csuhan/s2anet), [ORCNN](https://github.com/jbwang1997/OBBDetection), [mmrotate](https://github.com/open-mmlab/mmrotate), [yolov5obb](https://github.com/hukaixuan19970627/yolov5_obb), and some of my work.
