### ISSUE TITLE
ORN

### ISSUE THREAD

**Issue by DG205071** [ming71/rotate-yolov3#4]
你好，我想请假一下你是怎么实现ORN的，ORN貌似不匹配pytorch1.1以上版本

**Comment by ming71** [comment]
我忘了使用的是1.1还是1.0，程序在实验室机器上，现在没法返校不能查看，不过我使用的ORN你可以试试能否使用，放在这个[repo](https://github.com/ming71/CUDA/tree/master/ORN)了。

**Comment by DG205071** [comment]
更高版本的pytorch不支持吗

**Comment by ming71** [comment]
我没有试过，你可以试一下，我提供的repo里面写了个MINST的测试demo，直接run就可以

**Comment by DG205071** [comment]
我的anchor_cluster.txt是这样的44,44, 72,68, 135,118
在读取的时候出错了，特来像你请教

![1](https://user-images.githubusercontent.com/44964599/88265064-63202800-ccff-11ea-9c3d-8430933ea39e.jpg)

**Comment by ming71** [comment]
anchor_cluster.txt不是手动设置的，可以用kmeans聚类的结果文件，代码我已经在别的issue多次提过了。如果你手动设置，注意一下格式就行，这是个很简单的python错误，你到`utils/parse_config.py`里面看看读取的格式应该是怎样的。

**Comment by DG205071** [comment]
> anchor_cluster.txt不是手动设置的，可以用kmeans聚类的结果文件，代码我已经在别的issue多次提过了。如果你手动设置，注意一下格式就行，这是个很简单的python错误，你到`utils/parse_config.py`里面看看读取的格式应该是怎样的。

我用你的kmeans聚类的生成结果只有6个数，貌似不对，也许我可以看下.txt的具体格式

**Comment by ming71** [comment]
> > anchor_cluster.txt不是手动设置的，可以用kmeans聚类的结果文件，代码我已经在别的issue多次提过了。如果你手动设置，注意一下格式就行，这是个很简单的python错误，你到`utils/parse_config.py`里面看看读取的格式应该是怎样的。
> 
> 我用你的kmeans聚类的生成结果只有6个数，貌似不对，也许我可以看下.txt的具体格式

txt设置文件已上传，ORN代码也更新了
