### ISSUE TITLE
Training on ICDAR15 dataset error

### ISSUE THREAD

**Issue by tutu96177** [ming71/rotate-yolov3#6]
Hi ming71, your work is very wonderful, when I training on ICDAR15 dataset there is a problem , which is "icdar_608_care.txt file  is not exist in ${respo_root_dir}/utils/keans file dirctory " . How can I get this file ? Thanks.

**Comment by ming71** [comment]
You should generate the anchor setting file by yourself. I set it via `k-means` as reported in yolov2, and you can refer to my implemention [here](https://github.com/ming71/toolbox/blob/master/kmeans.py).
