### ISSUE TITLE
question to ryolo

### ISSUE THREAD

**Issue by MajorMango** [ming71/rotate-yolov3#7]
Hello ming71, Iam farly new to the whole topik.
I trainet my own Yolo dataset, and now i want to go further. I dont understand axacly how i can customize yolo do i have to do it only in the config file or do I have to write new code, is there some nice explanation out there ? you can recoment ? Sory for opening an issue for this I did not knew how to contact you elswehre. Thank You

**Comment by ming71** [comment]
hi, I think you'd better make it clear how the codebase  implemented. [This repo ](https://github.com/ultralytics/yolov3)is strongly recommended and is kind enough. if you want to customize yolo, just make changes on `cfg`  file. But you still have to write new codes once you wish to use some unimplemented module.
