### ISSUE TITLE
对这个项目很感兴趣，想请教下老哥，配置文件那里的mask和anchor是怎么来的

### ISSUE THREAD

**Issue by clw5180** [ming71/rotate-yolov3#8]
比如：mask = 144-215 anchors = 792, 2061, 3870, 6353, 9623, 15803 / 4.18, 6.48, 8.71  / -75, -60, -45, -30, -15 ,0,15, 30,45, 60,75, 90
我自己写了个倾斜版的anchor聚类，结果输出 9个 wha，比如对HRSC2016训练集进行聚类，得到
anchors: 153.60285000000002,29.688135000000017,-1.013242,  155.19675,29.394334999999984,0.6998453,  303.57180000000005,41.02582000000001,1.418342,  319.33545000000004,44.92217000000002,0.13387854999999999,  349.01929999999993,52.797129999999925,-0.7143881,  364.179,58.62256000000002,0.5916939,  397.41065000000003,66.58615,1.084582,  398.8361,69.37175500000006,-1.2166975,  533.6992,87.04564000000005,-0.2296711  Accuracy: 51.07%
请问如何转化为你的那种形式？

**Comment by ming71** [comment]
1. mask用于anchor的选择，没有具体的含义，你可以参考这个pytorch版本的[repo](https://github.com/ultralytics/yolov3)
2. 形式非常简单的，直接排列就行，具体你可以看看`utils/parse_config.PY`文件的函数，具体你调试一下就行，不难的。

**Comment by clw5180** [comment]
> 1. mask用于anchor的选择，没有具体的含义，你可以参考这个pytorch版本的[repo](https://github.com/ultralytics/yolov3)
> 2. 形式非常简单的，直接排列就行，具体你可以看看`utils/parse_config.PY`文件的函数，具体你调试一下就行，不难的。

好的，感谢。
